### PR TITLE
add ServerFactoryError type

### PR DESCRIPTION
**Pull request by fgimenez**
Towards https://github.com/giantswarm/ingress-operator/issues/23

Adds the type keeping the existing `ServerFactory`, so that old consumers of the library keep working

### CODE REVIEW

**Comment by fgimenez** [comment]
> Nitpick and doesn't matter in this case but I prefer vendor updates as a separate commit.

You are totally right, sorry, will remember next time :)

**Comment by fgimenez** [comment]
@xh3b4sd indeed, this is partial. I'll add the changes you mention, my initial idea was to include an additional field to the daemon command config with the error factory and then using either `Run` or `RunE` from `cobra.Command` depending on which one was set, let's see how it goes. 

Ok also about the changes to see this moving, i'll use ingress-operator for that.

**Comment by xh3b4sd** [comment]
What about this PR? Can we merge or close?

**Comment by fgimenez** [comment]
Better closing, haven't worked on it for a long time. We can reopen when retaken.

**Pull request closed without merging**
