### PR TITLE
Moves builds to use architect

### PR DESCRIPTION
**Pull request by JosephSalisbury**

### CODE REVIEW

**Comment by JosephSalisbury** [comment]
Eh, leaving this for now. Looks like `architect` doesn't detect any go code. Should be a small change there, but I don't want to do anymore boyscouting today.

**Comment by xh3b4sd** [comment]
What is going on here? Can we merge/delete?

**Comment by JosephSalisbury** [comment]
@xh3b4sd I need to finish this, give me timeeeeee

**Comment by xh3b4sd** [comment]
This is from August. How much time do you need?

**Comment by JosephSalisbury** [comment]
At most six months :D

**Comment by JosephSalisbury** [comment]
At most six months :D

**Comment by JosephSalisbury** [comment]
But seriously, closing this, and I'll just move microkit to circle 2, with architect. bam bam

**Comment by JosephSalisbury** [comment]
See https://github.com/giantswarm/microkit/pull/101

**Pull request closed without merging**
